kind: Simple
apiVersion: k3d.io/v1alpha4
metadata:
  name: keyholder
image: rancher/k3s:v1.20.4-k3s1
servers: 1
agents: 3
ports:
- port: 80:80
  nodeFilters:
    - loadbalancer
- port: 443:443
  nodeFilters:
    - loadbalancer
